application: bgi4ai
version: 1
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /blog/css
  static_dir: css
- url: /css
  static_dir: css
- url: /static
  static_dir: static
- url: /blog/static
  static_dir: static
- url: /blog/js
  static_dir: js
- url: /js
  static_dir: js
- url: /.*
  script: index.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
